image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
    - port: 3306
      onOpen: ignore
tasks:
    - init: >
        cp .env.example .env;
        psql -u root -e "CREATE DATABASE pokerswap";
        pipenv run init;
      command:
        pipenv install;
        pipenv run upgrade;
        pipenv run start;
    