"""empty message

Revision ID: 00769db0769b
Revises: d91ceef14060
Create Date: 2021-01-08 14:23:40.649033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00769db0769b'
down_revision = 'd91ceef14060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('blinds', sa.String(length=20), nullable=True))
    op.add_column('tournaments', sa.Column('buy_in_amount', sa.String(length=20), nullable=True))
    op.add_column('tournaments', sa.Column('starting_stack', sa.String(length=20), nullable=True))
    op.add_column('tournaments', sa.Column('structure_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'structure_link')
    op.drop_column('tournaments', 'starting_stack')
    op.drop_column('tournaments', 'buy_in_amount')
    op.drop_column('tournaments', 'blinds')
    # ### end Alembic commands ###
