"""empty message

Revision ID: 02361e308254
Revises: f22cd24fcc30
Create Date: 2020-07-07 21:14:39.046876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02361e308254'
down_revision = 'f22cd24fcc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hendon_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hendon_url')
    # ### end Alembic commands ###
