"""empty message

Revision ID: 05404e2ccb61
Revises: 323565c5286d
Create Date: 2020-11-05 21:52:50.716004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05404e2ccb61'
down_revision = '323565c5286d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'paid_at')
    # ### end Alembic commands ###
