"""empty message

Revision ID: 0fb0333f7516
Revises: f70116565aba
Create Date: 2020-07-20 16:39:25.335767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb0333f7516'
down_revision = 'f70116565aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('swap_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'swap_rating')
    # ### end Alembic commands ###
