"""empty message

Revision ID: 200fe0590e11
Revises: d1ad251014eb
Create Date: 2020-10-22 19:54:39.048365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200fe0590e11'
down_revision = 'd1ad251014eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('naughty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'naughty')
    # ### end Alembic commands ###
