"""empty message

Revision ID: 233527f67521
Revises: 4fad7a423ca2
Create Date: 2021-04-03 15:14:04.353533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233527f67521'
down_revision = '4fad7a423ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('unread_messages1', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('unread_messages2', sa.Integer(), nullable=True))
    op.drop_column('chats', 'unread_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('unread_messages', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('chats', 'unread_messages2')
    op.drop_column('chats', 'unread_messages1')
    # ### end Alembic commands ###
