"""empty message

Revision ID: 24f01ea19f82
Revises: c7104c5edc3c
Create Date: 2020-06-24 23:30:43.964493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f01ea19f82'
down_revision = 'c7104c5edc3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('casino', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'casino')
    # ### end Alembic commands ###
