"""empty message

Revision ID: 26efde54d3e8
Revises: f59b0e36e60e
Create Date: 2021-03-17 14:04:11.352303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26efde54d3e8'
down_revision = 'f59b0e36e60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('host_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'host_name')
    # ### end Alembic commands ###
