"""empty message

Revision ID: 406ba114b008
Revises: 05404e2ccb61
Create Date: 2020-12-17 17:30:16.098113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406ba114b008'
down_revision = '05404e2ccb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('confirmed_at', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'confirmed_at')
    # ### end Alembic commands ###
