"""empty message

Revision ID: 5943b3f65984
Revises: 88c0bc1276f5
Create Date: 2020-12-17 17:55:21.165727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5943b3f65984'
down_revision = '88c0bc1276f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('disputed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'disputed_at')
    # ### end Alembic commands ###
