"""empty message

Revision ID: 6c05aa8b1463
Revises: fde45ebca9f5
Create Date: 2020-07-23 01:31:18.851848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c05aa8b1463'
down_revision = 'fde45ebca9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'result_winnings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('result_winnings', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
