"""empty message

Revision ID: 85a531c3e954
Revises: 24f01ea19f82
Create Date: 2020-07-07 21:16:38.219085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a531c3e954'
down_revision = '24f01ea19f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('pokersociety_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'pokersociety_id')
    # ### end Alembic commands ###
