"""empty message

Revision ID: 882c5ff430d0
Revises: 26efde54d3e8
Create Date: 2021-03-31 09:54:10.740666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882c5ff430d0'
down_revision = '26efde54d3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('unread', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'unread')
    # ### end Alembic commands ###
