"""empty message

Revision ID: 88c0bc1276f5
Revises: 406ba114b008
Create Date: 2020-12-17 17:39:34.364944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c0bc1276f5'
down_revision = '406ba114b008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaps', sa.Column('disputed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swaps', 'disputed')
    # ### end Alembic commands ###
