"""empty message

Revision ID: a9e2ba5958fe
Revises: 5f2df9bd7359
Create Date: 2020-10-27 17:11:29.386535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e2ba5958fe'
down_revision = '5f2df9bd7359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('coin_update', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('result_update', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'result_update')
    op.drop_column('profiles', 'coin_update')
    # ### end Alembic commands ###
