"""empty message

Revision ID: 376246472e5d
Revises: 02361e308254
Create Date: 2020-07-09 00:33:09.887232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376246472e5d'
down_revision = '02361e308254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'results', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key(None, 'results', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'user_id')
    # ### end Alembic commands ###
