"""empty message

Revision ID: ae47ec163ef4
Revises: cbfd705dc762
Create Date: 2020-07-06 15:50:42.668959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae47ec163ef4'
down_revision = 'cbfd705dc762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('full_name', sa.String(length=40), nullable=True))
    op.drop_constraint('results_tournament_id_fkey', 'results', type_='foreignkey')
    op.drop_constraint('results_user_id_fkey', 'results', type_='foreignkey')
    op.drop_column('results', 'nickname')
    op.drop_column('results', 'last_name')
    op.drop_column('results', 'first_name')
    op.drop_column('results', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('first_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('nickname', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_foreign_key('results_user_id_fkey', 'results', 'users', ['user_id'], ['id'])
    op.create_foreign_key('results_tournament_id_fkey', 'results', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('results', 'full_name')
    # ### end Alembic commands ###
