"""empty message

Revision ID: b01bd4a82a88
Revises: f6bfa29816c8
Create Date: 2020-10-22 18:52:36.741203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01bd4a82a88'
down_revision = 'f6bfa29816c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_tournament_id_fkey', 'chats', type_='foreignkey')
    op.drop_column('chats', 'tournament_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chats_tournament_id_fkey', 'chats', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###
