"""empty message

Revision ID: ba63c8827cdf
Revises: f36bd1f95598
Create Date: 2021-04-07 11:42:45.313047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba63c8827cdf'
down_revision = 'f36bd1f95598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user1_name',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('chats', 'user1_pic',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('chats', 'user2_name',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('chats', 'user2_pic',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'user2_pic',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('chats', 'user2_name',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('chats', 'user1_pic',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('chats', 'user1_name',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###
