"""empty message

Revision ID: c7104c5edc3c
Revises: 2bd2bb8964db
Create Date: 2020-03-22 20:08:52.767214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7104c5edc3c'
down_revision = '2bd2bb8964db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'chats', 'profiles', ['user1_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'profiles', ['user2_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.alter_column('chats', 'user2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'user1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chats', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
