"""empty message

Revision ID: d5588aca4f67
Revises: 43b8fa701c4d
Create Date: 2021-03-05 11:10:42.044573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5588aca4f67'
down_revision = '43b8fa701c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('custom_address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'custom_address')
    # ### end Alembic commands ###
