"""empty message

Revision ID: f22cd24fcc30
Revises: ae47ec163ef4
Create Date: 2020-07-06 16:04:48.011473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22cd24fcc30'
down_revision = 'ae47ec163ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('place', sa.String(length=6), nullable=True))
    op.drop_column('results', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('results', 'place')
    # ### end Alembic commands ###
