"""empty message

Revision ID: f36bd1f95598
Revises: 233527f67521
Create Date: 2021-04-06 19:35:55.076577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36bd1f95598'
down_revision = '233527f67521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user1_name', sa.String(length=25), nullable=True))
    op.add_column('chats', sa.Column('user1_pic', sa.String(length=200), nullable=True))
    op.add_column('chats', sa.Column('user2_name', sa.String(length=25), nullable=True))
    op.add_column('chats', sa.Column('user2_pic', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'user2_pic')
    op.drop_column('chats', 'user2_name')
    op.drop_column('chats', 'user1_pic')
    op.drop_column('chats', 'user1_name')
    # ### end Alembic commands ###
