"""empty message

Revision ID: f59b0e36e60e
Revises: c42244152c89
Create Date: 2021-03-16 15:37:48.561889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59b0e36e60e'
down_revision = 'c42244152c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tournaments', 'profiles', ['host_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.drop_column('tournaments', 'host_id')
    # ### end Alembic commands ###
