"""empty message

Revision ID: f8058f8b1c33
Revises: 200fe0590e11
Create Date: 2020-10-23 16:22:41.715493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8058f8b1c33'
down_revision = '200fe0590e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
